plt.figure(figsize=(10, 5))
plt.subplot(2, 1, 1)
plt.plot(soc_log, label='SOC')
plt.ylabel('SOC')
plt.grid(True)
plt.legend()

plt.subplot(2, 1, 2)
plt.plot(power_log, label='P_PV+BESS', color='orange')
plt.ylabel('Power (kW)')
plt.xlabel('Hour')
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()
